### ISSUE TITLE
Banner ads on `ohli24.live`

### ISSUE THREAD

**Issue by eporubin** [easylist/KoreanList#1000]
There are banner ads at the top of the page and middle of the page on mobile: 
Top ads: `ohli24.live##.at-title`
![image](https://github.com/easylist/KoreanList/assets/33602691/ea24483f-01d0-4e90-8897-d482ea3b9366)
Middle banner: `ohli24.live###exon>a`
![image](https://github.com/easylist/KoreanList/assets/33602691/32f14291-f913-490e-95ee-d53955dc6b2e)
Thank you
I use ABP extension for Chrome on desktop and usually Ad Block Browser on mobile for testing with Korean list + Easy List + ABP filters

**Comment by tangible-idea** [comment]
The filter has added here: https://github.com/easylist/KoreanList/commit/ddbb8bcbf220ca81f22ecbc3813e01e4cbb7c811
Thank you for your contribution.
