### ISSUE TITLE
Invalid Filter

### ISSUE THREAD

**Issue by CbumDino** [easylist/KoreanList#1067]
Hey @tangible-idea, 
I hope you are doing well, 

Can you give a look at the filter: `adic.or.kr,agit*.xyz##.banner`
I was wondering if you could make it domain specific since ABP don't support wildcards on hidding filters ? 

Thank you in advance, 
Have a wonderful week.

**Comment by tangible-idea** [comment]
Yes, I have checked the history of it.
And looking into it. what domain should I block.
commit: https://github.com/easylist/KoreanList/commit/4bd157419b24bdd37896244ce5c736f0e02a1979
PR: https://github.com/easylist/KoreanList/pull/794

**Comment by tangible-idea** [comment]
[https://agit546.xyz/`](https://agit546.xyz/%3C/code%3E)
was what he tried to block.
and now the current domain number is https://agit612.xyz/
I'll put this one on auto domain update list.

**Comment by CbumDino** [comment]
Perfect @tangible-idea, thank you for looking into it. 
I'm closing this one, since it seems to be done.
