### ISSUE TITLE
Added blocklist one of our domain url (event.hackle.io)

### ISSUE THREAD

**Issue by wontak-hackle** [easylist/KoreanList#1079]
### DESC

2023년 10월 19일 이후로 자사의 SDK를 통해 전달되어지는 데이터가 다량 유실되는 현상이 감지되어 해당 이슈를 추적하던 중 Easylist(https://github.com/easylist/easylist)에서 @Khrin(https://github.com/Khrin) 사용자를 통해 핵클 회사의 도메인 중 하나가 추가되었으며 이를 통해 다수의 AD Blocking 어플리케이션을 통해 핵클 SDK를 사용하는 고객사의 서비스에서 해당 도메인을 차단되어 대량의 데이터가 유실되는 현상을 확인하였습니다.

추가된 파일의 URL 성격을 확인해 보았을 때 대부분 Scam 또는 Placement 와 같이 유해성 광고 또는 광고 지면에 관련된 주소들로 보여집니다. 핵클의 서비스 경우 한국에 위치한 A/B Testing SAAS 서비스를 제공하는 회사로 A/B Testing, Remote Config 또는 Feature Flag와 같이 고객사의 서비스 개선을 위한 B2B 서비스이며 광고와는 밀접한 관련 없습니다. Easylist에 추가된 URL 또한 데이터의 분배 또는 부분 배포와 같이 서비스 변경 사항에 대한 피드백을 위한 데이터를 고객사가 확인할 수 있도록 결과를 수집하기 위한 URL 입니다.

현재 해당 추가 사항으로 인해 서비스의 금전적 피해가 발생하고 있는 부분이라 정확한 상황 파악을 위해서 어떠한 이유로 인해 해당 주소가 추가 되었는지 문의하고 싶습니다.

혹시 필요로 하시다면 하단에 저의 이메일 주소 또한 함께 전달드리며 언제든 메일 보내주신다면 최대한 빠른 시일내에 답변드리도록 하겠습니다.

감사합니다.

wontak@hackle.io

### NEW ADDED

`||event.hackle.io^`

### 핵클 서비스

서비스 페이지 : https://www.hackle.io/en/
서비스 가이드 : https://docs-en.hackle.io/docs/getting-started-product-guide

**Comment by piquark6046** [comment]
@wontak-hackle

해당 commit를 따라가보면 [이 웹 사이트](https://www.wingeat.com/)에서 발견된 요청(`https://event.hackle.io/api/v2/w/events`)을 인용해서 추가된 것 같습니다.

<details><summary>스크린샷</summary>

![Screenshot from 2023-12-05 19-41-37](https://github.com/easylist/KoreanList/assets/98787049/1d67df43-28c8-4351-9b6e-23de7a0f0c40)


</details> 

EasyList 레포에 있는 EasyPrivacy라는 디텍터리가 있는데 그 디텍터리는 analytics나 telemetry 같은 요소를 제거하기 위해 있는 EasyPrivacy 필터 리스트를 위한 것입니다.
