### ISSUE TITLE
Ads / Ad spaces on https://m.fmkorea.com/best/6451608237

### ISSUE THREAD

**Issue by ryanbr** [easylist/KoreanList#1113]
Possible suggested filters;

```
m.fmkorea.com###fm_alert
||loader.fmkorea.com^
m.fmkorea.com##.fm_google_a
```

**Comment by tangible-idea** [comment]
`||loader.fmkorea.com^` looks good!

I could not find something related to `m.fmkorea.com###fm_alert` and `m.fmkorea.com##.fm_google_a`
Do you have any screenshots of it?

**Comment by ryanbr** [comment]
nvm I can't see  it now. safe to close
