### ISSUE TITLE
[Samsung Internet] Screen Flickering on m.blog.naver.com

### ISSUE THREAD

**Issue by mpccelon** [easylist/KoreanList#1399]
Reproduction Steps;

1. Easylist English + KoreanList (Issue replicated in Samsung Internet w/ ABP "English" + "Korean" filters)
2. Navigate to https://m.blog.naver.com/PostView.naver?blogId=potoi&logNo=223567874407&navType=by
3. Scroll to specific part of page 
4. Observe screen flickering

https://github.com/user-attachments/assets/fbe43483-9a06-40f4-9d2a-55eae8704101

**Comment by tangible-idea** [comment]
I am trying to reproduce it. but nothing happened.
Could you share with us the filter that you custom-applied?

**Comment by mpccelon** [comment]
We did not apply any custom filter.
This is done with ABP English + Korean filter (Updated to as of 30 minutes ago)

Please see video including ABP settings (apologies if low quality, there is 10MB video limit to github):
https://github.com/user-attachments/assets/4139cf02-c69b-4290-bafb-fa96c7d893f8

**Comment by tangible-idea** [comment]
@mpccelon 
I have re-checked with my other phone and added the filter against it.
and it works well as expected.
I am assuming it was the issue the banners were hidden while the ad script was still running on the page.

Please check the commit below :
https://github.com/easylist/KoreanList/commit/d362ad0f3a9670457f51b37d25606bbb6b9fea4d

**Comment by mpccelon** [comment]
Last question:
- Is koreanfilterlist@gmail.com still the preferred way to contact KoreanList?

If I recall email was sent regarding this a few days ago, but we are not sure if it is still active (it is listed in filter comments for KoreanList)

**Comment by tangible-idea** [comment]
@mpccelon 
Yes, I am in charge of the koreanfilterlist email.
but I probably forgot to get back to you.
you can CC this email as well "mark.choi@tangibleidea.net".

Thanks!
