### ISSUE TITLE
ygosu.com: Invalid filter

### ISSUE THREAD

**Issue by DavidLee3835** [easylist/KoreanList#425]
https://github.com/easylist/KoreanList/commit/99e302dc4f79150c17f73eecfc76327b2d7c1049

![image](https://user-images.githubusercontent.com/99162643/153408055-4847b62b-8ced-4a61-9737-1536fa31f9b7.png)

When those filters above applied to ABP or AdGuard, Images on websites disappears and alert message appears.
Please fix the filters.

**Comment by mango-king** [comment]
LEFT - enable easylist/KoreanList
RIGHT - disable easylist/KoreaList

---

![image](https://user-images.githubusercontent.com/99404989/153409447-23554bb8-6fd7-465b-9959-88df031dca48.png)

> https://ygosu.com/community/best_article/yeobgi/1902882/?type=daily&sdate=2022-02-10&frombest=Y
