### ISSUE TITLE
Ruliweb.com

### ISSUE THREAD

**Issue by mango-king** [easylist/KoreanList#427]
Please remove top banner

---

![image](https://user-images.githubusercontent.com/99404989/153409770-4d0ce842-e05f-4e52-b28b-e144e766caef.png)
![image](https://user-images.githubusercontent.com/99404989/153409855-15004f82-2f53-43b5-b117-b3f993ac9770.png)
> https://bbs.ruliweb.com/news/read/162121

**Comment by tangible-idea** [comment]
Issue has fixed by: https://github.com/easylist/KoreanList/commit/b25c69d48fb2cbc0e228f013e361c6c2d5664579
