### ISSUE TITLE
Popup at cafe24.com

### ISSUE THREAD

**Issue by edivaniadc** [easylist/KoreanList#459]
**Issue:**
Hide a popup on this Korean https://clfalfl.cafe24.com/?p=4237

**Suggestion:**
`cafe24.com##a[href^="https://open.kakao.com/"]`
`cafe24.com##.pum-close`

**Screenshot (mobile and desktop):**
<img width="1011" alt="dkt" src="https://user-images.githubusercontent.com/57706597/157498374-6297c860-f915-4760-9241-f8bfa26197e3.png">
<img width="334" alt="dkt2" src="https://user-images.githubusercontent.com/57706597/157498702-de26df62-20c8-42ca-8bbd-3a6d263adcdf.png">

**Comment by tangible-idea** [comment]
Hi, I have reviewed your suggestions. you can also PR.

**Comment by tangible-idea** [comment]
@edivaniadc  Hi, I have reviewed your suggestions. and it is good to go. you can also PR them.

**Comment by tangible-idea** [comment]
I have added it all :)
