### ISSUE TITLE
A: https://blacktoon173.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/KoreanList#525]
Hey @tangible-idea, have something for you: https://blacktoon173.com/webtoons/10824/1051181.html

<img width="1073" alt="Screenshot 2022-05-09 at 10 33 27" src="https://user-images.githubusercontent.com/65717387/167372509-3fced5f3-d2d2-4d91-aded-e3cce8313372.png">
<img width="923" alt="Screenshot 2022-05-09 at 10 38 08" src="https://user-images.githubusercontent.com/65717387/167372529-bbee214d-3ff1-49bc-8187-c3dd051cc784.png">

`||blacktoon173.com/poster_js` Should do the trick

**Comment by tangible-idea** [comment]
Umm ||blacktoon173.com/poster_js for which ads?

**Comment by felippesantos46** [comment]
Hey, sorry for the late response. On my pov, all of the banners 😄 !
<img width="1039" alt="Screenshot 2022-05-12 at 12 30 51" src="https://user-images.githubusercontent.com/65717387/168051226-9bc043e8-2473-463a-bdaa-b0ba6bed2080.png">

**Comment by tangible-idea** [comment]
Issue has fixed! thanks
