### ISSUE TITLE
Ads on naver.com (mobile)

### ISSUE THREAD

**Issue by monzta** [easylist/KoreanList#559]
On mobile emulation mode in Chrome I see ads and also on [Samsung Internet](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser) with [ABP](https://play.google.com/store/apps/details?id=org.adblockplus.adblockplussbrowser) and KoreanList. 

![nav](https://user-images.githubusercontent.com/8057368/173064495-40e4b0dd-fb56-4a31-b99c-ef600c2e626d.png)

My connection right now is not the best but it seems if you block `https://ssl.pstatic.net/tveta/libs/glad/glad-bridge.min.js`, the ad is gone. 

Also it seems on m.mail.naver.com ads show up above the inbox. Do you have an account and could check?

**Comment by tangible-idea** [comment]
@monzta I am looking for the ad on m.mail.naver.com. where did you find it?>

**Comment by monzta** [comment]
@tangible-idea It was reported to be right abovbe the first email. 

![naverkorean](https://user-images.githubusercontent.com/8057368/173529765-d78e4f1d-c53d-454f-a466-cff8e810817e.jpg)

It could also be that the suggested filter already blocks it but I cannot verify that as I don't have an account.

**Comment by tangible-idea** [comment]
@monzta I couldn't find it on my mail account. but it seems `||ssl.pstatic.net/tveta/libs/glad^$script,third-party` is working.
I've found a few more in finance section too.
https://finance.naver.com/item/main.naver?code=016600
and the same filter affects all.

**Comment by tangible-idea** [comment]
Issue has covered by : https://github.com/easylist/KoreanList/commit/5a03f8a96ee61e925b8a336e95524e7c2e84a562
Thank you!
