### ISSUE TITLE
https://m.ygosu.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/KoreanList#682]
Hey @tangible-idea,
Hope you are doing well,

I've spotted some Banners at https://m.ygosu.com/

https://m.ygosu.com/board/free/2214546/?searcht=&search=&m3=&page=
<img width="311" alt="Screenshot 2022-10-20 at 16 15 03" src="https://user-images.githubusercontent.com/65717387/196973890-c56251c8-5c72-4671-af76-ad74a2251a11.png">

<img width="315" alt="Screenshot 2022-10-20 at 16 14 46" src="https://user-images.githubusercontent.com/65717387/196973904-d531a077-b394-454d-9a6b-3c41f5f3f943.png">

**Comment by tangible-idea** [comment]
But ygosu.com is using ad-shield. It is almost impossible to block.

**Comment by felippesantos46** [comment]
@tangible-idea you are right ! We've tried also with x-path but the page seems to detect and break the css. 
We will get back to that one when we'll have more functionalities. For instance we can close that one.
Thank you once again :)
