### ISSUE TITLE
||cafeptthumb-phinf.pstatic.net^*type=*banner remove space

### ISSUE THREAD

**Issue by root-kernelhacker** [easylist/KoreanList#894]
||cafeptthumb-phinf.pstatic.net^*type=*banner

The banner will not appear with the filter rule above.  However, the banner seat remains as it is, and the banner seat is displayed in its place.  Which filter rule removes up to that spot?

**Comment by tangible-idea** [comment]
Hi 
Could you let me know which site did you have a problem?

**Comment by root-kernelhacker** [comment]
m.cafe.naver.com - cafe

A banner is attached to posts in the cafe.  Blocking this banner is the previous filter rule.  This filter rule does not display the banner image, but it cannot delete the banner image area.

**Comment by root-kernelhacker** [comment]
Done !

add filter

m.cafe.naver.com##[class='banner_add bottom']

^^
