### ISSUE TITLE
naver cafe banner add

### ISSUE THREAD

**Issue by root-kernelhacker** [easylist/KoreanList#906]
1 Existing addition (general banner)
m.cafe.naver.com##[class='banner_add bottom']

2. Newly added (product trading post banner)
m.cafe.naver.com##[class='banner_add']

Thank you !

**Comment by tangible-idea** [comment]
Is it inside the Naver cafe contents?

**Comment by root-kernelhacker** [comment]
Yes, this is a banner included in the Naver Cafe's posts that trade products.
