### ISSUE TITLE
NAVER CAFE BANNER FILTER !

### ISSUE THREAD

**Issue by root-kernelhacker** [easylist/KoreanList#937]
The existing filter rules include the following filters.
 m.cafe.naver.com##[class='banner_add bottom']
 
However, the filter rule below must also be added and included.  I've already made an offer, but is there a reason why it's still not included?  Please also include the rules below.

 m.cafe.naver.com##[class='banner_add']

Thank you !

**Comment by tangible-idea** [comment]
Your request has been merged. Thank you!
